import Footer from "@/components/Molecules/Footer/Footer";
import Navbar from "@/components/Molecules/Navbar/Navbar";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
     weight: "500",
     subsets: ["latin"],
     display: "swap",
});

export const metadata: Metadata = {
     title: "Vivek Maurya || Portfolio",
     description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
     return (
          <html lang="en" className={roboto.className}>
               <head>
                    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
               </head>

               <body>
                    <Navbar />
                    {children}
                    <Footer />
               </body>
          </html>
     );
}
